# frozen_string_literal: true
#
# Firebird: a write that returns values read through fetch/fetch_one either
# WORKS and commits, or fails LOUD and CLEAN - it never leaves its transaction
# open.
#
# Measured on the lab's Firebird 5 with fb 0.10.0: UPDATE/DELETE ... RETURNING
# and INSERT ... SELECT ... RETURNING come back as a real cursor (Firebird 5
# returns multi-row RETURNING as a result set), so they work. A single-row
# INSERT ... VALUES ... RETURNING is a SINGLETON result: Firebird hands its
# values back only through isc_dsql_execute2's OUTPUT sqlda, which the gem
# never passes, so the first fetch raises "Unknown cursor / Cursor is not open"
# (-504). No call in the gem can return them (Connection#execute hands back an
# unopened cursor), so that one form is refused with a clear error.
#
# The dangerous part was what the failure left behind. Connection#query starts
# an AUTOMATIC transaction when none is open and commits it only when the fetch
# completes; the failed fetch skipped that, so the transaction - holding the
# uncommitted write - stayed open on the connection. Every later statement ran
# inside it, and DDL from anyone on that table blocked ("object in use"): the
# first issue-133 run on the lab hung on its DROP TABLE.
#
# Contract now: outside an explicit transaction the automatic transaction is
# ROLLED BACK (nothing written, nothing locked) and a clear
# FirebirdDriver::ReturningNotSupported names the workaround. Inside an
# explicit transaction the caller's transaction is left for the caller's own
# rollback, and the same clear error is raised.
#
# Every example runs under spec/support/firebird_watchdog.rb, so a leaked
# transaction FAILS within 20s instead of hanging the lab.
#
# REAL Firebird only - NO mocks. Env-gated on TINA4_TEST_FIREBIRD_URL; the skip
# reason carries "firebird" and no provisioned-service keyword, like
# spec/firebird_rollback_spec.rb.

require "spec_helper"
require "uri"
require "socket"
require_relative "support/firebird_watchdog"

RSpec.describe "Firebird: a RETURNING write read through fetch fails loud and leaves no transaction open",
               firebird_watchdog: true do
  def fb_returning_url
    ENV["TINA4_TEST_FIREBIRD_URL"].to_s
  end

  def fb_returning_connect
    Tina4::Database.new(fb_returning_url,
                        username: ENV.fetch("TINA4_TEST_FIREBIRD_USERNAME", "SYSDBA"),
                        password: ENV.fetch("TINA4_TEST_FIREBIRD_PASSWORD", "masterkey"))
  end

  def fb_returning_table
    "issue133_rb_fb_ret"
  end

  def fb_returning_skip_reason
    return "TINA4_TEST_FIREBIRD_URL not set - firebird returning spec skipped" if fb_returning_url.empty?

    begin
      require "fb"
    rescue LoadError
      return "fb gem not installed - firebird returning spec skipped"
    end
    uri = URI.parse(fb_returning_url)
    TCPSocket.new(uri.host, uri.port || 3050).close
    nil
  rescue StandardError
    "firebird not reachable at #{fb_returning_url} - spec skipped"
  end

  # Rows a SECOND connection can see - i.e. what was committed.
  def fb_returning_committed_rows
    other = fb_returning_connect
    other.fetch_one("SELECT COUNT(*) AS c FROM #{fb_returning_table}", [], no_cache: true)[:c].to_i
  ensure
    other&.close rescue nil
  end

  # Run the statement, return what it raised. The transaction-state
  # assertions come FIRST in each example, so they are measured whatever
  # the error turns out to be.
  def fb_returning_error
    yield
    nil
  rescue StandardError => e
    e
  end

  def fb_returning_tx_open?(db)
    db.send(:current_driver).connection.transaction_started
  end

  before(:each) do
    reason = fb_returning_skip_reason
    skip(reason) if reason

    @db = fb_returning_connect
    begin
      @db.execute("DROP TABLE #{fb_returning_table}")
    rescue StandardError
      nil # first run: no table yet
    end
    @db.execute("CREATE TABLE #{fb_returning_table} " \
                "(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body VARCHAR(100) NOT NULL)")
  end

  after(:each) do
    next unless @db

    # Never DROP while a transaction may be open on this connection - that is
    # the very lock this spec is about.
    begin
      @db.rollback
    rescue StandardError
      nil
    end
    begin
      @db.execute("DROP TABLE #{fb_returning_table}")
    rescue StandardError
      nil
    ensure
      @db.close rescue nil
    end
  end

  it "fetch_one(INSERT ... RETURNING) raises a clear error, writes nothing and leaves no transaction open" do
    error = fb_returning_error do
      @db.fetch_one("INSERT INTO #{fb_returning_table} (body) VALUES (?) RETURNING id", ["returning"], no_cache: true)
    end

    expect(fb_returning_tx_open?(@db)).to be(false),
                                          "the failed RETURNING left its transaction open on the connection"
    expect(fb_returning_committed_rows).to eq(0)
    expect(error).to be_a(Tina4::Drivers::FirebirdDriver::ReturningNotSupported),
                     "expected the clear error, got #{error.class}: #{error&.message}"
    expect(error.message).to match(/RETURNING.*rolled back/m)

    # The connection is still usable, and a plain write still autocommits.
    @db.execute("INSERT INTO #{fb_returning_table} (body) VALUES (?)", ["plain"])
    expect(fb_returning_committed_rows).to eq(1)
  end

  it "fetch(UPDATE ... RETURNING) and fetch_one(DELETE ... RETURNING) DO work on Firebird 5 and commit exactly once" do
    @db.execute("INSERT INTO #{fb_returning_table} (body) VALUES (?)", ["before"])
    id = @db.fetch_one("SELECT id FROM #{fb_returning_table}", [], no_cache: true)[:id]

    updated = @db.fetch("UPDATE #{fb_returning_table} SET body = ? WHERE id = ? RETURNING id", ["after", id],
                        no_cache: true)
    expect(updated.records.map { |row| row[:id] }).to eq([id])
    expect(fb_returning_tx_open?(@db)).to be(false)
    expect(fb_returning_committed_rows).to eq(1)
    body = fb_returning_connect.then do |other|
      other.fetch_one("SELECT body FROM #{fb_returning_table}", [], no_cache: true)[:body]
    ensure
      other.close rescue nil
    end
    expect(body.to_s.strip).to eq("after")

    deleted = @db.fetch_one("DELETE FROM #{fb_returning_table} WHERE id = ? RETURNING id", [id], no_cache: true)
    expect(deleted[:id]).to eq(id)
    expect(fb_returning_committed_rows).to eq(0)
  end

  it "inside an explicit transaction it raises the clear error and leaves the rollback to the caller" do
    @db.start_transaction
    @db.execute("INSERT INTO #{fb_returning_table} (body) VALUES (?)", ["in the transaction"])
    error = fb_returning_error do
      @db.fetch_one("INSERT INTO #{fb_returning_table} (body) VALUES (?) RETURNING id", ["returning"], no_cache: true)
    end

    expect(fb_returning_tx_open?(@db)).to be(true), "the caller's own transaction must not be ended for it"
    expect(error.class.name).to eq("Tina4::Drivers::FirebirdDriver::ReturningNotSupported")
    expect(error.message).to match(/explicit transaction/)
    @db.rollback
    expect(fb_returning_tx_open?(@db)).to be(false)
    expect(fb_returning_committed_rows).to eq(0)
  end

  it "a plain SELECT through fetch still works and ends its automatic transaction (control)" do
    @db.execute("INSERT INTO #{fb_returning_table} (body) VALUES (?)", ["read me"])
    expect(@db.fetch("SELECT body FROM #{fb_returning_table}", [], no_cache: true).records.length).to eq(1)
    expect(fb_returning_tx_open?(@db)).to be(false)
  end
end
